SWP391_MiniStore/Controllers/AccessController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using SWP391_MiniStore.Models.Domain;
using SWP391_MiniStore.Data;
using SWP391_MiniStore.Models.ViewModels;

namespace SWP391_MiniStore.Controllers
{
    public class AccessController : Controller
    {
        private readonly MiniStoreDbContext _dbContext;

        public AccessController(MiniStoreDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Login()
        {
            ClaimsPrincipal claimsUser = HttpContext.User;
            
            string? errorMessage = TempData["ErrorMessage"] as string;
            if (!string.IsNullOrEmpty(errorMessage))
            {
                ModelState.AddModelError(string.Empty, errorMessage);
            }

            return claimsUser?.Identity?.IsAuthenticated == true ? RedirectToAction("Index", "Home") : View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel modelLogin)
        {
            StoreStaff? user = await _dbContext.StoreStaff.FirstOrDefaultAsync(staff =>
                (staff.Email == modelLogin.EmailOrUsername || staff.Username == modelLogin.EmailOrUsername) &&
                staff.Password == modelLogin.Password);

            if (user != null)
            {
                List<Claim> claims = new List<Claim>();
                
                claims.Add(new Claim(ClaimTypes.NameIdentifier, user.StaffID.ToString()));

                if (!string.IsNullOrEmpty(user.Username))
                {
                    claims.Add(new Claim(ClaimTypes.Name, user.Username));
                }

                if (!string.IsNullOrEmpty(user.Email))
                {
                    claims.Add(new Claim(ClaimTypes.Email, user.Email));
                }

                if (!string.IsNullOrEmpty(user.PhoneNumber))
                {
                    claims.Add(new Claim(ClaimTypes.MobilePhone, user.PhoneNumber));
                }

                if (!string.IsNullOrEmpty(user.Password))
                {
                    claims.Add(new Claim("Password", user.Password));
                }

                if (user.Dob != null)
                {
                    claims.Add(new Claim(ClaimTypes.DateOfBirth, user.Dob.Value.ToString()));
                }

                if (!string.IsNullOrEmpty(user.Address))
                {
                    claims.Add(new Claim(ClaimTypes.StreetAddress, user.Address));
                }

                if (!string.IsNullOrEmpty(user.StaffRole))
                {
                    claims.Add(new Claim(ClaimTypes.Role, user.StaffRole));
                }

                if (user.HourlyRate != null)
                {
                    claims.Add(new Claim("HourlyRate", user.HourlyRate.Value.ToString()));
                }

                if (user.StaffStatus != null)
                {
                    claims.Add(new Claim("StaffStatus", user.StaffStatus.Value.ToString()));
                }

                ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims,
                    CookieAuthenticationDefaults.AuthenticationScheme);

                AuthenticationProperties properties = new AuthenticationProperties()
                {
                    AllowRefresh = true,
                    IsPersistent = modelLogin.RememberMe
                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity), properties);

                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError(string.Empty, "User not found");
            TempData["ErrorMessage"] = "User not found";

            return RedirectToAction("Login");
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }
    }
}

SWP391_MiniStore/Controllers/AttendanceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SWP391_MiniStore.Data;

namespace SWP391_MiniStore.Controllers
{
    [Authorize]
    public class AttendanceController : Controller
    {
        private readonly MiniStoreDbContext _dbContext;

        public AttendanceController(MiniStoreDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize(Roles = "Manager")]
        public IActionResult ManagerWorkSchedule()
        {
            return View();
        }

    }
}

SWP391_MiniStore/Controllers/StaffManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SWP391_MiniStore.Data;
using SWP391_MiniStore.Models.Domain;
using SWP391_MiniStore.Models.ViewModels;
using System.Net;

namespace SWP391_MiniStore.Controllers
{
    [Authorize(Roles = "Manager")]
    public class StaffManagementController : Controller
    {
        private readonly MiniStoreDbContext _dbContext;

        public StaffManagementController(MiniStoreDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var staffList = await _dbContext.StoreStaff.ToListAsync();
            StoreStaff? currentManager = await this.GetCurrentStoreStaffAsync(_dbContext, HttpContext);
            if (currentManager != null)
            {
                staffList.RemoveAll(s => s.StaffID == currentManager.StaffID);
            }
            return View(staffList);
        }

        [HttpGet]
        public IActionResult Add()
        {
            string? errorMessage = TempData["ErrorMessage"] as string;
            if (!string.IsNullOrEmpty(errorMessage))
            {
                ModelState.AddModelError(string.Empty, errorMessage);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddStaffViewModel addStaffRequest)
        {
            if(addStaffRequest.Password != addStaffRequest.ConfirmPassword)
            {
                ModelState.AddModelError(string.Empty, "Password and confirm password must be the same");
                TempData["ErrorMessage"] = "Password and confirm password must be the same";
                return RedirectToAction("Add");
            }
            if (addStaffRequest.Password != null && addStaffRequest.Username != null && addStaffRequest.Password.Contains(addStaffRequest.Username))
            {
                ModelState.AddModelError(string.Empty, "Password cannot contain the username");
                TempData["ErrorMessage"] = "Password cannot contain the username";
                return RedirectToAction("Add");
            }

            var s = new StoreStaff()
            {
                StaffID = Guid.NewGuid(),
                Username = addStaffRequest.Username,
                Email = addStaffRequest.Email,
                PhoneNumber = addStaffRequest.PhoneNumber,
                Password = addStaffRequest.Password,
                Dob = addStaffRequest.Dob,
                Address = addStaffRequest.Address,
                StaffRole = addStaffRequest.StaffRole,
                HourlyRate = addStaffRequest.HourlyRate,
                StaffStatus = true
            };

            await _dbContext.StoreStaff.AddAsync(s);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var s = await _dbContext.StoreStaff.FirstOrDefaultAsync(s => s.StaffID == id);
            if (s != null)
            {
                string? errorMessage = TempData["ErrorMessage"] as string;
                if (!string.IsNullOrEmpty(errorMessage))
                {
                    ModelState.AddModelError(string.Empty, errorMessage);
                }

                var viewModel = new UpdateStaffViewModel()
                {
                    StaffID = s.StaffID,
                    Username = s.Username,
                    Email = s.Email,
                    PhoneNumber = s.PhoneNumber,
                    Password = s.Password,
                    ConfirmPassword = s.Password,
                    Dob = s.Dob,
                    Address = s.Address,
                    StaffRole = s.StaffRole,
                    HourlyRate = s.HourlyRate,
                    StaffStatus = s.StaffStatus
                };
                return View(viewModel);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateStaffViewModel updateStaffRequest)
        {
            if (updateStaffRequest.Password != updateStaffRequest.ConfirmPassword)
            {
                ModelState.AddModelError(string.Empty, "Password and confirm password must be the same");
                TempData["ErrorMessage"] = "Password and confirm password must be the same";
                return RedirectToAction("View", new { id = updateStaffRequest.StaffID });
            }
            if (updateStaffRequest.Password != null && updateStaffRequest.Username != null && updateStaffRequest.Password.Contains(updateStaffRequest.Username))
            {
                ModelState.AddModelError(string.Empty, "Password cannot contain the username");
                TempData["ErrorMessage"] = "Password cannot contain the username";
                return RedirectToAction("View", new { id = updateStaffRequest.StaffID });
            }

            var s = await _dbContext.StoreStaff.FindAsync(updateStaffRequest.StaffID);
            if (s != null)
            {
                s.Username = updateStaffRequest.Username;
                s.Email = updateStaffRequest.Email;
                s.PhoneNumber = updateStaffRequest.PhoneNumber;
                s.Password = updateStaffRequest.Password;
                s.Dob = updateStaffRequest.Dob;
                s.Address = updateStaffRequest.Address;
                s.StaffRole = updateStaffRequest.StaffRole;
                s.HourlyRate = updateStaffRequest.HourlyRate;
                s.StaffStatus = updateStaffRequest.StaffStatus;

                await _dbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateStaffViewModel updateStaffRequest)
        {
            var s = await _dbContext.StoreStaff.FindAsync(updateStaffRequest.StaffID);
            if (s != null)
            {
                _dbContext.StoreStaff.Remove(s);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

SWP391_MiniStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SWP391_MiniStore</title>

    <link rel="apple-touch-icon" sizes="180x180" href="~/images/logos/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/images/logos/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/images/logos/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SWP391_MiniStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SWP391_MiniStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <partial name="_NavPartial" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark">
        <div class="container">
            <span style="color: azure;">&copy; 2023 - </span><a href="https://github.com/minhtam7355/SWP391_MiniStore" style="color: azure; text-decoration: none;">SWP391_MiniStore</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SWP391_MiniStore/Views/Shared/_LayoutForECommerce.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - SWP391_MiniStore</title>

    <link rel="apple-touch-icon" sizes="180x180" href="~/images/logos/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/images/logos/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/images/logos/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SWP391_MiniStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SWP391_MiniStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 text-uppercase justify-content-end pe-3">
                        <li class="nav-item">
                            <a class="nav-link me-4 text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-4 text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-4 text-dark" asp-area="" asp-controller="#" asp-action="#">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-4 text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <partial name="_NavPartial" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark">
        <div class="container-fluid text-start pt-3" style="background-color: #212934; color: #cfd6e1; padding-left: 300px; padding-right: 300px;">
            <div class="row" style="line-height: 1.5;">
                <div class="col-6">
                    <img class="mb-3" src="~/images/logos/MiniStore-Logo.png" width="300" alt="logo">
                    <p style="white-space: initial;">Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore amet erat.</p>
                    <p><i class="bi bi-geo-alt-fill"></i> 123 Street, HoChiMinh, VietNam</p>
                    <p><i class="bi bi-envelope-fill"></i> info@example.com</p>
                    <p><i class="bi bi-telephone-fill"></i> +84 1 1234 1234</p>
                </div>
                <div class="col-3">
                    <p><h3 class="font-weight-bold border-bottom pb-3 border-light mb-4">Quick Links</h3></p>
                    <p><a href="#">Home</a></p>
                    <p><a href="#">About</a></p>
                    <p><a href="#">Shop</a></p>
                    <p><a href="#">Detail</a></p>
                    <p><a href="#">Cart</a></p>
                    <p><a href="#">Checkout</a></p>
                    <p><a href="#">Contact</a></p>
                </div>
                <div class="col-3">
                    <p><h3 class="font-weight-bold border-bottom pb-3 border-light mb-4">Products</h3></p>
                    <p><a href="#">Mac</a></p>
                    <p><a href="#">iPad</a></p>
                    <p><a href="#">iPhone</a></p>
                    <p><a href="#">Watch</a></p>
                    <p><a href="#">AirPods</a></p>
                </div>
            </div>
        </div>
        <div class="container">
            <span style="color: azure;">&copy; 2023 - </span><a href="https://github.com/minhtam7355/SWP391_MiniStore" style="color: azure; text-decoration: none;">SWP391_MiniStore</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SWP391_MiniStore/Views/Shared/_NavPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims

@{
    ClaimsPrincipal claimsUser = Context.User;
}

@if (claimsUser.Identity != null && claimsUser.Identity.IsAuthenticated && claimsUser.HasClaim(c => c.Type == ClaimTypes.Role && c.Value == "Manager"))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="StaffManagement" asp-action="Index">Staff Management</a>
    </li>
    <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="ViewReports">View Reports</a> @*Implement Later*@
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Attendance" asp-action="ManagerWorkSchedule">Work Schedule</a>
    </li>
}
else if (claimsUser.Identity != null && claimsUser.Identity.IsAuthenticated && claimsUser.HasClaim(c => c.Type == ClaimTypes.Role && c.Value == "Sales"))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="###" asp-action="###"></a> @*Implement Later*@
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Login"></a>
    </li>
}
else if (claimsUser.Identity != null && claimsUser.Identity.IsAuthenticated && claimsUser.HasClaim(c => c.Type == ClaimTypes.Role && c.Value == "Guard"))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="###" asp-action="###"></a> @*Implement Later*@
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Login"></a>
    </li>
}
else
{

}